[package]
name = "aql-engine-datafusion"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
aql-adapter-api = { path = "../aql-adapter-api" }
aql-catalog = { path = "../aql-catalog" }
aql-model = { path = "../aql-model" }
async-trait.workspace = true
datafusion = { workspace = true, features = ["sql"] }
futures.workspace = true
sqlparser = { workspace = true, features = ["visitor"] }
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
aql-adapter-codex = { path = "../aql-adapter-codex" }
tokio = { workspace = true, features = ["macros", "rt"] }
