[package]
name = "aql-release"
edition.workspace = true
license.workspace = true
version.workspace = true
publish = false

[dependencies]
clap = { workspace = true, features = ["derive"] }
flate2 = { workspace = true, features = ["zlib-rs"] }
hex.workspace = true
rustix = { workspace = true, features = ["fs", "process"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
tempfile.workspace = true

[lints]
workspace = true
