[package]
name = "aql-config"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
aql-fs = { path = "../aql-fs" }
cap-std.workspace = true
fs2.workspace = true
rand.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
toml.workspace = true

[lints]
workspace = true
