[package]
name = "aql-config"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
rand.workspace = true
rustix = { workspace = true, features = ["fs"] }
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
toml.workspace = true

[lints]
workspace = true
